### ISSUE TITLE
Задание 1. Запуск приложения. Ошибки при запуске, зависает на экране загрузки.

### ISSUE THREAD

**Issue by wecansu** [oknosoft/metadata-devtraining#10]
Прошу помощи! Выполняю задания в OS X.
Не могу пройти последний пункт, запуск приложения.
 "Теперь также вызываем "Сценарии npm" - "start". После некоторых раздумий должна открыться страница в Google Chrome с адресом localhost:3000, и в ней мы увидим наш helloworld."
Страница в гуглохроме открывается, выдает сообщение о ошибках, после его закрытия заставка загрузки бесконечно долго висит.
Окно с ошибками на скриншоте.
![2018-01-24 23 55 29](https://user-images.githubusercontent.com/35488227/35356901-db78d1a0-0162-11e8-90c1-dcb2c8faa9c8.png)

**Comment by nmivan** [comment]
У меня была такая же ошибка, так и не понял ее происхождения. Переходите к задаче 2, там ошибка уходит.

**Comment by wecansu** [comment]
Да, ушла ошибка. А при нажатии на пункты меню говорит ошибка авторизации, это так и должно быть? Или поискать что не так сделал?

**Comment by DBMainUser** [comment]
У меня тоже самое

>А при нажатии на пункты меню говорит ошибка

**Comment by blackmixer** [comment]
> Да, ушла ошибка. А при нажатии на пункты меню говорит ошибка авторизации, это так и должно быть? Или поискать что не так сделал?


1 Проверьте настройки на стороне 1с (Интеграция: настройка) zone (по умолчанию 0) - Зона (область данных) Абонента
2 В интерфейсе на стороне браузера проверьте Настройки => Подключение к базе данных => Область данных
Область данных  = Зона в 1с 

 (Умолчания задаются в app.settings.js)

https://github.com/oknosoft/helloworld/blob/72ce09930cfdf55fa5c6ba8871a4b53b4b99c2e8/config/app.settings.js#L42

после проверить логин и пароль

**Comment by nmivan** [comment]
Проблемы с авторизацией после второй задачи - это нормально. Скоро будет третья.

**Comment by wecansu** [comment]
Хорошо! Ждем третью)
