### ISSUE TITLE
Задача 1. Проблемы с авторизацией

### ISSUE THREAD

**Issue by santaur** [oknosoft/metadata-devtraining#11]
Демка в браузере запустилась, при попытке открыть список документов "Перемещение ДС" вижу: "Для доступа к данному разделу, необходима авторизация"
Захожу в авторизацию, под полем логина и пароля красная надпись "Сервер недоступен, ошибка сети или сервера"

В консоли браузера:
```
couchdb/_session 
Failed to load resource: the server responded with a status of 404 (Not Found)
pouchdb.authentication.min.js:1 
POST http://localhost:3000/couchdb/_session 404 (Not Found)
```

**Comment by nmivan** [comment]
При решении первой и второй задач на авторизацию не обращайте внимания.

**Comment by santaur** [comment]
Проблема осталась и после 3 задачи. Не удаётся зайти ни под гостем, ни под другим пользователем.
![capture](https://user-images.githubusercontent.com/35830269/35811718-21ced85a-0aca-11e8-9aa2-63884f6ec714.PNG)

**Comment by unpete** [comment]
> POST http://localhost:3000/couchdb/_session 404 (Not Found)

А какой ответ сервера вы ожидали, отправляя такой запрос?
У вас ведь, couchdb не висит на порту 3000 в папке /couchdb/
Варианты решения:
- изменить путь couchdb в диалоге авторизации на закладке _Подключение_
- изменить умолчание в app.settings.js
- настроить маршрутизацию средствами nginx или nodejs

**Comment by santaur** [comment]
Евгений, спасибо за ответ.
Я поменял путь к коучу в app.settings.js:
`couch_path: "//localhost:5984/" + lsprefix,`

Путь couchdb в диалоге авторизации на закладке _Подключение_ поставил: http://localhost:5984/hw_

Окно авторизации не изменилось, пишет сервер недоступен. В консоли при этом пишет:
```
OPTIONS http://localhost:5984/_session 405 (Method Not Allowed)
Failed to load http://localhost:5984/_session: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 405.
```

**Comment by wecansu** [comment]
У меня так же пишет и не авторизуется

**Comment by unpete** [comment]
А CORS в Couchdb кто за вас включать будет?

**Comment by nmivan** [comment]
@unpete , мой косяк, я про CORS не написал.

**Comment by santaur** [comment]
Уже нашёл в сети информацию, что эта ошибка связяна с КОРС, но в конфигурации 1С в обработке настройки интеграции нет кнопки "Включить КОРС". У Вас в уроке видел, что она должна быть.

**Comment by santaur** [comment]
Способ исправления:
в Fauxton открыть Configuration - CORS - Enable CORS - All domains ( * )
