### ISSUE TITLE
Задача 2. ошибка.

### ISSUE THREAD

**Issue by torbeev** [oknosoft/metadata-devtraining#12]
Иван, выполнил все действия. запускаю
"Failed to compile
./node_modules/react-virtualized/dist/es/List/List.js
281:117-150 '../Grid' does not contain an export named 'bpfrpt_proptype_NoContentRenderer'.
This error occurred during the build time and cannot be dismissed."

**Comment by torbeev** [comment]
![image](https://user-images.githubusercontent.com/17550874/35668591-d8afc2ca-0753-11e8-8039-f8f882b61031.png)

**Comment by nmivan** [comment]
Это первая задача? Когда именно делали?

Там платформа развивается, и компоненты внешние тоже, и иногда все это сильно обгоняет в развитии helloworld.

**Comment by torbeev** [comment]
Делал сегодня, задача 2. npm upgrade делал.

**Comment by unpete** [comment]
Это хороший повод:
- разобраться, как работает `npm`, структура package.json, команды, версии, зависимости
- узнать/понять, какие библиотеки использованы внутри метадаты и снаружи для сборки и запуска приложения

Контекст, с которым работает веб-программист шире, чем в 1С, в языке, на котором приходится думать больше слов и выражений, но это вполне помещается в голову

**Comment by torbeev** [comment]
Приветствую, Евгений. Так и делаю, в тексте ошибки есть информация для решения. npm init. npm upgrade.
