### ISSUE TITLE
Задача 4

### ISSUE THREAD

**Issue by torbeev** [oknosoft/metadata-devtraining#13]
При записи документа в веб'ке получаю ошибку.

"TypeError: msg is not a function
DocCash_moving.webpackJsonp../src/metadata/documents/doc_cash_moving.js.__webpack_exports__.a.DocCash_moving.before_save
G:/NBP/helloworld/src/metadata/documents/doc_cash_moving.js:20
  17 | if(this.sender.empty() && this.recipient.empty()) {
  18 | 
  19 |   msg.show_msg({
-> 20 |     title: msg('mandatory_title'),
  21 |     type: 'alert-error',
  22 |     text: msg('mandatory_one_cashbox')
  23 |   });
View compiled
"

![image](https://user-images.githubusercontent.com/17550874/35911079-93493448-0c1a-11e8-941b-3e124f8c6b7b.png)

**Comment by santaur** [comment]
Была такая ошибка, когда документ не полностью заполнял. Попробуйте заполнить все реквизиты у документа.

**Comment by torbeev** [comment]
Заполнил все поля, записалось.
