### ISSUE TITLE
Загрузка документов в 1С

### ISSUE THREAD

**Issue by santaur** [oknosoft/metadata-devtraining#14]
Как загрузил документ в 1С:

1. в обработке Настройка интеграции на странице Загрузка проставил все галочки Использование
2. нажал Прочитать из КоучДБ
3. в колонке Since проставил 1 везде где был 0
4. далее в конфигураторе в модуле ИнтеграцияСериализацияСервер в процедуре CouchDB_ЗагрузитьИзменения закомментировал строку `ИнтеграцияПереопределяемый.ПроверитьТипИРеквизитыЗагружаемыхДанных(МенеджерИМета, meta, Изм.doc);` т.к. этой процедуры в конфигурации нету
5. создал документы Перемещение денег в сервисе
6. в 1С запустил рег. задание Сессии лёгкого клиента, созданные документы появились в базе

Проблема: если созданный документ изменить в сервисе, изменения не передаются в 1С. Документ в базе 1С остаётся в том виде, как загрузился первоначально. Но если создать в сервисе новый документ, то вместе с новым документом в 1С придут и изменения старого документа.

**Comment by nmivan** [comment]
> в обработке Настройка интеграции на странице Загрузка проставил все галочки Использование

все не надо было, ну да ладно. 

> в колонке Since проставил 1 везде где был 0

это лишнее, Since - это идентификатор обмена, формируемый CouchDB, аналог номера сообщения обмена в 1С. Если стоит 0, то просто обмена ни разу не было.

В остальном - все отлично.

**Comment by santaur** [comment]
> Если стоит 0, то просто обмена ни разу не было.

Там к воде проверка этого поля на ЗначениеЗаполнено, и если 0, то обмен просто не запускается

А что по поводу описанной проблемы с обновлением документов?

**Comment by nmivan** [comment]
> А что по поводу описанной проблемы с обновлением документов?

На нее пока стоит забить. Если будем исправлять все недоработки тестовой среды, то застрянем навсегда.
