### ISSUE TITLE
Вопрос по синхронизации с кэшированием

### ISSUE THREAD

**Issue by sergeishumsky** [oknosoft/metadata-devtraining#22]
Получилось пройти все задания, попробовал по аналогии добавить свой документ, все работает.

Но работает, если стоит флажок "Прямое подключение без кэширования". Если он снят, то в обратную сторону с легкого клиента данные не попадают в 1с. Более того, они сохраняются в легком клиенте, но в couchdb их тоже не удалось найти. После логоф/логон данные остаются в легком клиенте все равно. Можете подсказать, как работает/должен работать механизм в случае, если этот флажок снят.

**Comment by unpete** [comment]
Посмотрите исходники https://github.com/oknosoft/metadata.js/tree/develop/packages/metadata-pouchdb
Скорее всего, вы настроили свойство параметра сеанса `zone_demo` равным текущей `zone`.
В этом случае, синхронизация базы `doc` по умолчанию запускается в одну сторону: от сервера к браузеру.
Если `zone_demo !== zone`, синхронизация `doc` работает в обе стороны.
Кроме значений `zone_demo` и `zone`, важны настройки текущего пользователя и отдела абонентов, которому принадлежит текущий пользователь.
Пользователю может быть назначен режим `push_only`, а для отдела абонентов можно запретить режим `offline`, принудительно установив `direct`

**Comment by sergeishumsky** [comment]
Спасибо, установил zone_demo отличным от zone, все получилось
