### ISSUE TITLE
Ошибка при meta:prebuild

### ISSUE THREAD

**Issue by rsyuzyov** [oknosoft/metadata-devtraining#24]
Делаю
`npm run meta:prebuild`
, получаю ошибку:
```
> helloworld@2.0.16-beta.56 meta:prebuild C:\1c\home\rsyuzyov\metadata\web
> node scripts/meta.prebuild.js

  prebuild: Читаем конструктор и плагины +0ms
  prebuild: Создаём объект MetaEngine +789ms
  prebuild: Настраиваем MetaEngine +7ms
  prebuild: Читаем описание метаданных из CouchDB http://localhost:5984/hw_ +
  prebuild: Подключение к http://localhost:5984/hw_meta/ +44ms
  prebuild: Не удалось получить объект meta из CouchDB
  prebuild: Проверьте логин, пароль и строку подключения +10ms
  prebuild: { error: 'not_found',
  prebuild:   reason: 'missing',
  prebuild:   name: 'not_found',
  prebuild:   status: 404,
  prebuild:   message: 'missing',
  prebuild:   docId: 'meta' } +1ms
```
Объект meta в hw_meta действительно отсутствует, но есть meta_patch:
![image](https://user-images.githubusercontent.com/7994115/38659753-43fb5568-3e44-11e8-946b-ef94ad6811cc.png)
Если запрашивать его, то выполнение завершается успешно.
Как правильней будет: переименовать meta_patch в meta или запрашивать meta_patch вместо meta?

**Comment by unpete** [comment]
Любой проект metadata обязан иметь префикс. Например, у helloworld префикс hw_
Если  вам зачем-то захотелось пересобрать файл метаданных, объект hw_meta должен существовать в couchdb и содержать осмысленную информацию.

**Comment by rsyuzyov** [comment]
Евгений, спасибо за ответ!
С префиксом порядок, проблема не в том, что база hw_meta не найдена, а в том, что объект meta не существует. То есть, если в meta.prebuild.js вместо
return db.get('meta')
сделать
return db.get('meta_patch')
то пересборка проходит нормально.
Поэтому и возник исходный вопрос :)
А пересборку захотелось потому, что мне ведь не helloworld в конечном итоге нужен, а собственное приложение со своими метаданными. Ну и просто посмотреть, что будет, конечно.

**Comment by rsyuzyov** [comment]
Или я не уловил мысль про префикс?

**Comment by unpete** [comment]
В базе hw_meta должен существовать объект meta + по вашему желанию, объекты meta_patch, meta_patch_1 ... meta_patch_n

**Comment by rsyuzyov** [comment]
Воот, у меня объект meta отсутствует, а meta_patch есть. При этом база hw_meta создана через настройку интеграции из базы 1С для hellowrold. Ручных вмешательств не было. Это нормально? Хочется понять, почему нет ожидаемого объекта и как должно быть по-правильному.
Я просто еще плохо понимаю кухню, если скажете, что мне пока этот вопрос стоит отложить, я отложу.
