### ISSUE TITLE
Полнотекстовый поиск, как это сделано в 1С

### ISSUE THREAD

**Issue by rsyuzyov** [oknosoft/metadata-devtraining#25]
Возможно это история не для devtraining, но подобный вопрос определенно будет возникать именно у неофитов вроде меня.
В общем захотели мы попробовать сделать подбор номенклатуры и практически сразу уткнулись в то, что полнотекстовый поиск, как в 1С, отсутствует:
![image](https://user-images.githubusercontent.com/7994115/38660385-7c2f2a5c-3e46-11e8-93b8-729eda4c7ec5.png)
После изучения темы стало понятно, что:
- couchdb не умеет полнотекст самостоятельно
- couchdb-lucene протух
- интеграция с elastic через rivers протухла
- интеграция с elastic через logstash-beats, к сожалению, уже совсем не бесшовная и по факту требует организовывать работу с индексом отдельно от couchdb.
Но самое страшное оказалось в том, что в 1С реализовано не совсем то, точнее совсем не то, что обычно понимается под полнотекстовым поиском: наверное правильней было бы назвать это быстрым множественным поиском вхождения подстрок...
Все опробованные fti-сервисы (fulltext index) замечательно сделают поиск по фразе "Подшипники для КПП", но привычные, милые сердцу пользователя 1С сокращения типа "подшип зад втор вал" приводят их в ступор. Хотя такой поиск, безусловно, тоже очень интересен.

А вопросы у меня такие:
-Может ли кто что подсказать, помочь советом или примером?
- Вообще у кого какой опыт есть в этом направлении?
- Какие есть идеи о том, какие еще направления можно покопать?

**Comment by unpete** [comment]
Вопрос уточните. Про "милые сердцу пользователя 1С сокращения" я ничего не знаю.
Если нужен поиск по множественному вхождению подстрок, можно сделать обычный map-индекс по всем словам наименования и фильтровать объединяя результаты этого индекса.
Если обоснуете полезность этой задачи, можно задействовать этот алгоритм в типовом поиске metadata-react

**Comment by rsyuzyov** [comment]
Спасибо за ответ!

По сути вопрос такой "как сделать поиск, аналогичный поиску в динсписках в 1С?"
В общем после того, как осознал, что конкретно нужно, тоже понял, что это решаемо средствами couchdb, буду пробовать. Но если вопрос покажется Вам достойным реализации, буду только рад,  конечно.

Про "классический" полнотекст вопрос пока перешел для меня в разряд академических, так как это не то, что нужно, хотя и интересно. В описании просто выложил пройденный путь, чтобы сэкономить время другим, если столкнутся.

Про "милые сердцу" - это я так как раз про встроенный поиск в динсписках).
Примеры:
- в контрагентах или в журнале реализаций пользователи пишут что-то вроде "ооо биз уч" вместо "ООО "Бизнес-учет" - поиск позволяет лениться
- подбор товаров привел в топике - у продавцов это основная функция при работе с подбором
- поиск по комментариям: если в https://hello.oknosoft.ru/doc.cash_moving/list в строке поиска написать "рус", то будет найден документ по комментарию "просто текст по русски":
![image](https://user-images.githubusercontent.com/7994115/38661703-2a18313c-3e4b-11e8-8d3d-a7ff871593d6.png)
, но если написать "рус текст", то результат будет пустой.
