### ISSUE TITLE
Ошибка npm build

### ISSUE THREAD

**Issue by vad1c** [oknosoft/metadata-devtraining#27]
Failed to compile.
Module not found: Error: Can't resolve '@material-ui/core/SvgIcon' in 'E:\proektNetbeans\hello\helloworld\node_modules\@material-ui\icons\utils'
Подскажите, где искать?
Запустил npm start  и получил
./src/index.js
  Line 39:  componentWillMount is deprecated since React 16.3.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount  react/no-deprecated
Search for the keywords to learn more about each error.

**Comment by unpete** [comment]
См.: #28

**Comment by unpete** [comment]
дублирует #28, #29, см.: https://github.com/oknosoft/metadata-devtraining/issues/29#issuecomment-404616152 - закрываю
