### ISSUE TITLE
1 задание, Ошибка сборки и запуска

### ISSUE THREAD

**Issue by ipm71** [oknosoft/metadata-devtraining#28]
Доброго времени суток,
у меня не получается собрать и запустить приложение,

"D:\Program Files\nodejs\npm.cmd" "run-script" "build"

> helloworld@2.0.16-beta.56 build D:\Projects\metadata-devtraining\helloworld
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '@material-ui/core/SvgIcon' in 'D:\Projects\metadata-devtraining\helloworld\node_modules\@material-ui\icons\utils'

Готово.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! helloworld@2.0.16-beta.56 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the helloworld@2.0.16-beta.56 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-06-04T21_56_32_655Z-debug.log

**Comment by unpete** [comment]
Трудно что-то добавить к такому подробному комментарию, который вам дал `npm`: не установлен пакет `@material-ui\icons`.
Вероятно, обновив свой репозиторий из github, вы забыли выполнить
````bash
npm i
npm up
npm prune
````
Дублирует #28

**Comment by ipm71** [comment]
Добрый день,
после клонирования в netbeans 
и после команды npm i
выходит сообщение

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @material-ui/icons@1.1.0 requires a peer of @material-ui/core@^1.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of babel-eslint@^7.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

пробовал несколько раз переустанавливать все по шагам, все равно одно и тоже выходит
