### ISSUE TITLE
Задание 1. Ошибка при NPM BUILD в NetBeans. При NPM START эта же ошибка уже в браузере.

### ISSUE THREAD

**Issue by AlexanderDemidovich** [oknosoft/metadata-devtraining#29]
В NetBeans:

"C:\nodejs\npm.cmd" "run-script" "build"

> helloworld@2.0.16-beta.56 build C:\metadata\helloworld
> node scripts/build.js

Creating an optimized production build...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! helloworld@2.0.16-beta.56 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the helloworld@2.0.16-beta.56 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\1\AppData\Roaming\npm-cache\_logs\2018-07-05T08_38_55_261Z-debug.log
Failed to compile.

./src/index.js
  Line 39:  componentWillMount is deprecated since React 16.3.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount  react/no-deprecated

Search for the keywords to learn more about each error.

Готово.

В браузере:

Failed to compile
./src/index.js
  Line 39:  componentWillMount is deprecated since React 16.3.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount  react/no-deprecated

Search for the keywords to learn more about each error.
This error occurred during the build time and cannot be dismissed.

Смотрел дргие Issues, там описаны  похожие проблемы. По советам из других Issues делал последовательность команд:
git pull
npm i
npm prune
npm up

Пакет React версии 16.4.1. 
Ничего не помогает. 
В чём может быть дело, помогите разобраться???

**Comment by RapeFactory** [comment]
> Line 39: componentWillMount is deprecated since React 16.3.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount react/no-deprecated

Надо, возможно, или игнорировать это предупреждение от Реакта, либо изменить метод на UNSAFE. На 16.4 уже не получится со старым названием.

**Comment by AlexanderDemidovich** [comment]
Когда заменяю на UNSAFE_componentWillMount, получается следующее:

"C:\nodejs\npm.cmd" "run-script" "build"

> helloworld@2.0.16-beta.56 build C:\metadata\helloworld
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

./src/index.js
Module parse failed: Unexpected token (46:11)
You may need an appropriate loader to handle this file type.
| 
|   render() {
|     return <Provider store={store}>
|       <RootView
|         history={history}


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! helloworld@2.0.16-beta.56 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the helloworld@2.0.16-beta.56 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\1\AppData\Roaming\npm-cache\_logs\2018-07-05T09_47_32_147Z-debug.log
Готово.

И то же в браузере.
Подобное описано в #23 , рекомендации оттуда не помогают. 

А как можно проигнорировать это предупреждение? В браузере тогда тогда тоже всё выполнится?

Также пробовал ставить более ранние версии пакетов React, но тогда  npm build вообще выдаёт массу ошибок, красных строк и т. д.

Что можно ещё посмотреть?

**Comment by RapeFactory** [comment]
В режиме отладки запускается? Начните с этого. И переставить `node_modules`
```
rm -R node_modules
rm package-lock.json
npm cache clean --force
npm install
```

**Comment by AlexanderDemidovich** [comment]
Переустановка node_modules не помогла. Те же проблемы, по прежнему.
А каким образом можно запустить в режиме отладки? Используется NetBeans 8.2, Windows 64 bit.
В меню "Отладка" пункты почему-то недоступны.

**Comment by RapeFactory** [comment]
@AlexanderDemidovich npm start

**Comment by RapeFactory** [comment]
Подождем подсказки от сообщества. Но претензии у npm очень странные.

> Could not open index.js in the editor.

**Comment by AlexanderDemidovich** [comment]
Ну что скажут уважаемые сенсеи? К сожалению, проблема до сих пор так и не решена, нет никакой возможности двигаться дальше.

**Comment by unpete** [comment]
Вода камень точит.
Не прошло и 4 месяцев, как нашлось время выпустить обновление, в котором учтены breaking changes `material-ui v1.0`, `react v16.4`, `pouchdb v7.0`
Всех благодарю за терпение, см.: https://github.com/oknosoft/metadata.js/commit/c649989867b844c3f9fa06c5178bf0fbfc179b01 и https://github.com/oknosoft/helloworld/commit/9c2b4193fdd7a2407c352e35744d347251782634

**Comment by AlexanderDemidovich** [comment]
После обновлений вопрос не решился. Может, нужна какая-то определенная версия NODE JS, NPM?
Вот скриншот:

C:\metadata\helloworld>npm run-script build

> helloworld@2.0.17-beta.3 build C:\metadata\helloworld
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

./src/index.js
Module parse failed: Unexpected token (46:11)
You may need an appropriate loader to handle this file type.
|
|   render() {
|     return <Provider store={store}>
|       <RootView
|         history={history}


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! helloworld@2.0.17-beta.3 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the helloworld@2.0.17-beta.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\1\AppData\Roaming\npm-cache\_logs\2018-07-13T08_09_20_823Z
-debug.log

C:\metadata\helloworld>

**Comment by RapeFactory** [comment]
> Module parse failed: Unexpected token (46:11)

Что в этой строке?

**Comment by AlexanderDemidovich** [comment]
src \ index.js, строка 46:
return <Provider store={store}>

**Comment by AlexanderDemidovich** [comment]
"return <Provider store={store}>"

**Comment by AlexanderDemidovich** [comment]
Скобки ещё фигурные перед Provider и после {store}, здесь не отображает.
return Provider store={store}

**Comment by AlexanderDemidovich** [comment]
Вот скрин, 46-я строка выделена.
![image](https://user-images.githubusercontent.com/40691092/42681387-338f02da-8690-11e8-9555-23bfb1a76822.png)

**Comment by RapeFactory** [comment]
Похоже на то, что не распознается JSX разметка. Из-за чего не знаю.

**Comment by unpete** [comment]
Я сделал необходимое и достаточное для запуска со свежими библиотеками (см. https://hello.oknosoft.ru). Дальше - самостоятельно.
Если не получается дружбы с npm - плюньте. Значит оно вам просто не подходит.

**Comment by RapeFactory** [comment]
Сделайте еще попытку с чистого листа, с нового клона. И проследите за установкой всех пакетов из зависимостей.

**Comment by AlexanderDemidovich** [comment]
Спасибо. Всё заработало, со свежими библиотеками, после установки Node JS версии 8.11.3 и создания нового клона.
