### ISSUE TITLE
Ошибка при нажатии "Создать базы и пользователей"

### ISSUE THREAD

**Issue by wecansu** [oknosoft/metadata-devtraining#3]
#Добрый день! 
Идея с сообществом супер!
"Идем на закладку "Регистрация", нажимаем "Создать базы и пользователей", она пару секунд думает и говорит, что Выполнено. Можно сходить в браузер по сохраненной ссылке на Fauxton, и в списке баз (Databases) увидеть наши hw_0_ram, hw_0_doc, hw_0_meta - это и есть созданные базы."
У меня после пары секунд сообщает об ошибке, которая записана в журнал регистрации, но там только ссылка на ошибку в модуле "ИнтеграцияСериализацияСервер"
![2018-01-16 16 48 32](https://user-images.githubusercontent.com/35488227/34992121-26c01ad8-fadd-11e7-9942-ed01199ede34.png)
![2018-01-16 16 48 02](https://user-images.githubusercontent.com/35488227/34992122-26e6bff8-fadd-11e7-88a8-81ed5674a091.png)

**Comment by wecansu** [comment]
В уроке вы пишите что нам нужна версия 2.0 CouchDB. Я с офф сайта скачал 2.1, 2.0 там нет вроде. Видимо из за этого ошибка!

**Comment by unpete** [comment]
> скачал 2.1, 2.0 там нет вроде. Видимо из за этого ошибка!

Маловероятно.
2.0 и 2.1 работают практически одинаково.
2.1 повела себя нестабильно в одном из наших проектов, поэтому возникла рекомендация использовать 2.0.

Проверьте:
- доступен ли couchdb по пути, указанному на первой закладке панели администрирования (хост, порт, префикс проекта)
- обладает ли пользователь, от имени которого 1С подключается к couchdb админскими правами в couchdb

Если с подключением и правами всё хорошо, поставьте точку останова в 1С и рассмотрите request и response более детально.

**Comment by wecansu** [comment]
В 2.1 нет таблицы _users , может в этом дело?

**Comment by wecansu** [comment]
На первой вкладке подключение выполняется
1С у меня запущена под Wine, может от этого проблема.

**Comment by wecansu** [comment]
Такой ответ при проверке подключения:
"{
	"doc": {
		"error": "not_found",
		"reason": "Database does not exist."
	},
	"ram": {
		"error": "not_found",
		"reason": "Database does not exist."
	},
	"user": {
		"ok": true,
		"userCtx": {
			"name": "admin",
			"roles": [
				"_admin"
			]
		},
		"info": {
			"authentication_db": "_users",
			"authentication_handlers": [
				"cookie",
				"default"
			],
			"authenticated": "default"
		}
	}
}"

**Comment by wecansu** [comment]
Если ввожу в браузере http://127.0.0.1:5984/_users
в ответ: {"error":"not_found","reason":"Database does not exist."}
Судя по коду в модуле при создании пользователя по этому адресу 1С пытается добавить запись.

**Comment by unpete** [comment]
Про это в основной ветке есть [задача](https://github.com/oknosoft/metadata.js/issues/286)

**Comment by nmivan** [comment]
Это чего за хулиган ворвался в школу и сел за парту до ее открытия :)

**Comment by wecansu** [comment]
Понял! Спасибо)
Школу скромно упомянули на инфостарте)

**Comment by wecansu** [comment]
Помогло, когда донастроил couchdb

**Comment by wecansu** [comment]
Помогло только создать системные базы данных _global_changes, _users, _replicator, однако база 1С все равно не может создать пользователей в couchdb.
По отладке при попытке записи пользователя ошибка, в журнале регистрации {"error":"unknown_error","reason":"undefined"}

**Comment by wecansu** [comment]
Может ли быть причиной то что я работаю в OS X и 1С у меня запускается под Wine?

**Comment by nmivan** [comment]
Теоретически да. Работать под OS X - непременное условие?

**Comment by unpete** [comment]
В couchdb нет секретиков, всё взаимодействие происходит по http. Любые
действия с couchdb можно выполнить прямо из консоли с помощью curl или
wget. Вероятность того, что в 1С-ной части под mac есть фатальные ошибки
HTTPСоединения очень низкая.

**Comment by nmivan** [comment]
Вероятность есть. У меня как-то была ошибка работы с CouchDB из-за заплаты в Windows 10.

**Comment by wecansu** [comment]
Проблема решена. Гугл вывел на такое обсуждение https://www.bountysource.com/issues/51922281-couchdb-2-1-1-crashes-and-keeps-restarting-macos-high-sierra-10-13-1
Вариант решения там приведен.
Проблема в отсутствии некоторых пакетов из-за которых couchdb на ОС Х не корректно работал через http запросы.

**Comment by unpete** [comment]
@wecansu спасибо, не зря мы советовали 2.0.
