### ISSUE TITLE
Не активны кнопки в левой части экрана

### ISSUE THREAD

**Issue by pit24** [oknosoft/metadata-devtraining#4]
После выполнения всех пунктов первого задания, на открывшейся странице, нажатие на кнопки в левой части экрана не приводит ни к каким действиям. Работают только кнопки верхней панели. Firefox 57.0.4 (64-бит)

**Comment by nmivan** [comment]
На это пока не обращаем внимания. Среду разработки удалось развернуть?

**Comment by pit24** [comment]
Да. Спасибо.

**Comment by nmivan** [comment]
@pit24 , вторую задачу решали? После этого кнопки должны исправиться.

**Comment by pit24** [comment]
Да, решил. Теперь все в порядке.
