### ISSUE TITLE
Не работает левое выпадающее меню

### ISSUE THREAD

**Issue by shalimski** [oknosoft/metadata-devtraining#6]
Выполнил первое задание, после запуска проекта в меню слева не работает ни одна кнопка

![image](https://user-images.githubusercontent.com/1501405/35021022-cfac5044-fb69-11e7-80f4-c9e2f256a25d.png)

**Comment by nmivan** [comment]
На это пока не обращаем внимания. Среда у вас развернулась?

**Comment by shalimski** [comment]
Да, проект запускается.
