### ISSUE TITLE
Застрял на п.6 База 1С

### ISSUE THREAD

**Issue by a-grinyuk** [oknosoft/metadata-devtraining#7]
По инструкции:

5. CouchDB

> При установке задаем администратора и его пароль - сильно мудрить не надо,
> достаточно admin/admin, это же локальная СУБД для разработки. 

При установке никакие вопросы не задавались по поводу ввести логин и пароль админа. Я это сделал непосредственно в Web-интерфейсе.

Теперь к самой  ошибке.

Застрял на этапе
Идем на закладку "Регистрация", нажимаем "Создать базы и пользователей"

У меня вываливается ошибка:
{ОбщийМодуль.ИнтеграцияСериализацияСервер.Модуль(2472)}: CouchDB_Пользователи: (подробности в журнале регистрации)

HTTPЗапрос
{
	"name": "Гость",
	"password": "333",
	"roles": [
		"doc_editor",
		"ram_reader",
		"ref:98cb9c1c-563f-11e6-82b8-d85d4c80ec2a",
		"pwd:2463598333",
		"prefix:Г",
		"suffix:"
	],
	"type": "user"
}

HTTPОтвет.КодСостояния = 404
{"error":"not_found","reason":"Database does not exist."}

**Comment by unpete** [comment]
Ответ есть здесь: #3 
Вообще, полезно просматривать не только текущие, но и решенные [issues](https://github.com/oknosoft/metadata-devtraining/issues?q=is%3Aissue+is%3Aclosed)

**Comment by a-grinyuk** [comment]
Знал бы прикуп, жил бы в Сочи. Спасибо.
