### ISSUE TITLE
По заданию 2

### ISSUE THREAD

**Issue by DBMainUser** [oknosoft/metadata-devtraining#8]
Форкнул базу хелловорлд позавчера. Пул реквесты показывает что нет отличий между окнософт v2 и моей базой v2. И да все кнопки всех панелей были у меня изначально активны. Так что для задания 2 прес икс ту вин.

**Comment by unpete** [comment]
Разработка v2 ведётся в branch develop.
С высокой вероятностью, вы сравнили свой репозиторий с branch master

**Comment by DBMainUser** [comment]
нет именно что с v2 сравнивал. Сравнение с мастером дает кучу доработок в изменениях: похоже за все эти годы.

**Comment by DBMainUser** [comment]
![compare](https://user-images.githubusercontent.com/35705084/35320308-20db19dc-0105-11e8-8d6c-2bd30e4f671c.PNG)

**Comment by a-grinyuk** [comment]
Должно быть наоборот. Слева вы, справа главный репозиторий.
http://bpteam.net/blog/2016/01/12/обновление-форка-репозиторирия-чере/

**Comment by DBMainUser** [comment]
![compare2](https://user-images.githubusercontent.com/35705084/35320838-0592b606-0107-11e8-8e05-096ee671d052.PNG)
Так все равно ничего нет к сравнению

**Comment by a-grinyuk** [comment]
Может быть вы уже обновились? Или когда форк создавали там уже были внесены последние изменения.

**Comment by DBMainUser** [comment]
Да, коллега. Я примерно о том и подозревал еще в первом посте, спасибо за правослалвную инструкцию

**Comment by nmivan** [comment]
Спасибо, @a-grinyuk ! В первый раз свершилось то, ради чего было создано это сообщество - люди помогли друг другу, и не понадобилась помощь @unpete .
