### ISSUE TITLE
Борьба с подключением CouchDB  к 1С

### ISSUE THREAD

**Issue by DBMainUser** [oknosoft/metadata-devtraining#9]
https://stackoverflow.com/questions/37401355/cant-create-server-admin-in-couchdb помогло решить мне что подключение к CouchDB нужно вести на порт 5986 (а не 5984). Иначе шла ошибка: событие CouchDB_Записать {"error":"not_found","reason":"Database does not exist."}. 

Также подшаманил саму базу 1c:
![349c6861fa88f17483ef794a4a82a121](https://user-images.githubusercontent.com/35705084/35298745-f370617e-00a4-11e8-82d2-6f31bb55303a.png) Иначе ругался на отсутствие names у объекта.

**Comment by nmivan** [comment]
Такое ощущение, что у вас CouchDB 1.7. Это так?

**Comment by DBMainUser** [comment]
![default](https://user-images.githubusercontent.com/35705084/35402455-7b16b2a2-021e-11e8-8b9c-cc5bff3b7a18.png)

**Comment by unpete** [comment]
Доработку admins-users-names-roles я уже включил в библиотеку интеграции.
В своих экспериментах повторить проблему не смог, но с доработкой, действительно, безопаснее.

Информация про порт 5986 вместо 5984 - из другой оперы. Кратко не описать.

**Comment by DBMainUser** [comment]
> Кратко не описать.
Спасибо, пока надобности нет. Ребята со стаковерфлоу главное подкинули решение, а теоретическую часть мы опустим.
